# coding: utf-8

"""
    Fingerprint server API

    Schema describes Fingerprint public server API  # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.paginated_response import PaginatedResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestPaginatedResponse(unittest.TestCase):
    """PaginatedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedResponse(self):
        """Test PaginatedResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.paginated_response.PaginatedResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
