# coding: utf-8

"""
    Fingerprint Pro Server API

    Fingerprint Pro Server API provides a way for validating visitors’ data issued by Fingerprint Pro.  # noqa: E501

    OpenAPI spec version: 3
    Contact: support@fingerprint.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import fingerprint_pro_server_api_sdk
from fingerprint_pro_server_api_sdk.models.browser_details import BrowserDetails  # noqa: E501
from fingerprint_pro_server_api_sdk.rest import ApiException


class TestBrowserDetails(unittest.TestCase):
    """BrowserDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBrowserDetails(self):
        """Test BrowserDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = fingerprint_pro_server_api_sdk.models.browser_details.BrowserDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
