# coding: utf-8

"""
    Fingerprint server API

    Schema describes Fingerprint public server API  # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import fingerprint_pro_server_api_sdk
from fingerprint_pro_server_api_sdk.models.ip_location_city import IPLocationCity  # noqa: E501
from fingerprint_pro_server_api_sdk.rest import ApiException


class TestIPLocationCity(unittest.TestCase):
    """IPLocationCity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIPLocationCity(self):
        """Test IPLocationCity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = fingerprint_pro_server_api_sdk.models.ip_location_city.IPLocationCity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
