# coding: utf-8

"""
    Fingerprint server API

    Schema describes Fingerprint public server API  # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.confidence import Confidence  # noqa: E501
from swagger_client.rest import ApiException


class TestConfidence(unittest.TestCase):
    """Confidence unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfidence(self):
        """Test Confidence"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.confidence.Confidence()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
