# coding: utf-8

"""
    Fingerprint Server API

    Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.   # noqa: E501

    OpenAPI spec version: 3
    Contact: support@fingerprint.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import re  # noqa: F401
from typing import Dict, List, Optional  # noqa: F401
from fingerprint_pro_server_api_sdk.base_model import BaseModel
from fingerprint_pro_server_api_sdk.models.products import Products


class EventsGetResponse(BaseModel):
    """
    Contains results from all activated products - Fingerprint Pro, Bot Detection, and others.

    NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'products': 'Products'
    }

    nullable_map = {
        'products': False
    }

    attribute_map = {
        'products': 'products'
    }

    def __init__(self, products=None):  # noqa: E501
        """EventsGetResponse - a model defined in Swagger"""  # noqa: E501
        self._products = None
        self.discriminator = None
        self.products = products

    @property
    def products(self) -> Products:
        """Gets the products of this EventsGetResponse.  # noqa: E501


        :return: The products of this EventsGetResponse.  # noqa: E501
        """
        return self._products

    @products.setter
    def products(self, products: Products):
        """Sets the products of this EventsGetResponse.


        :param products: The products of this EventsGetResponse.  # noqa: E501
        """
        if products is None:
            raise ValueError("Invalid value for `products`, must not be `None`")  # noqa: E501

        self._products = products

