# coding: utf-8

"""
    Server API v3 (deprecated)

    > 🚧 Deprecation Notice > > This version of Server API is marked as deprecated starting on **Jan 7th 2026** according to our [API Deprecation Policy](https://dev.fingerprint.com/reference/api-deprecation-policy). If you still use this version, please follow our [migration guide](https://dev.fingerprint.com/reference/migrating-from-server-api-v3-to-v4) to migrate from this deprecated version to the new one.  Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.   # noqa: E501

    OpenAPI spec version: 3
    Contact: support@fingerprint.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import re  # noqa: F401
from typing import Dict, List, Optional  # noqa: F401
from fingerprint_pro_server_api_sdk.base_model import BaseModel
from fingerprint_pro_server_api_sdk.models.integration_subintegration import IntegrationSubintegration


class Integration(BaseModel):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'version': 'str',
        'subintegration': 'IntegrationSubintegration'
    }

    nullable_map = {
        'name': False,
        'version': False,
        'subintegration': False
    }

    attribute_map = {
        'name': 'name',
        'version': 'version',
        'subintegration': 'subintegration'
    }

    def __init__(self, name=None, version=None, subintegration=None):  # noqa: E501
        """Integration - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._version = None
        self._subintegration = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if version is not None:
            self.version = version
        if subintegration is not None:
            self.subintegration = subintegration

    @property
    def name(self) -> Optional[str]:
        """Gets the name of this Integration.  # noqa: E501

        The name of the specific integration, e.g. \"fingerprint-pro-react\".  # noqa: E501

        :return: The name of this Integration.  # noqa: E501
        """
        return self._name

    @name.setter
    def name(self, name: Optional[str]):
        """Sets the name of this Integration.

        The name of the specific integration, e.g. \"fingerprint-pro-react\".  # noqa: E501

        :param name: The name of this Integration.  # noqa: E501
        """

        self._name = name

    @property
    def version(self) -> Optional[str]:
        """Gets the version of this Integration.  # noqa: E501

        The version of the specific integration, e.g. \"3.11.10\".  # noqa: E501

        :return: The version of this Integration.  # noqa: E501
        """
        return self._version

    @version.setter
    def version(self, version: Optional[str]):
        """Sets the version of this Integration.

        The version of the specific integration, e.g. \"3.11.10\".  # noqa: E501

        :param version: The version of this Integration.  # noqa: E501
        """

        self._version = version

    @property
    def subintegration(self) -> Optional[IntegrationSubintegration]:
        """Gets the subintegration of this Integration.  # noqa: E501


        :return: The subintegration of this Integration.  # noqa: E501
        """
        return self._subintegration

    @subintegration.setter
    def subintegration(self, subintegration: Optional[IntegrationSubintegration]):
        """Sets the subintegration of this Integration.


        :param subintegration: The subintegration of this Integration.  # noqa: E501
        """

        self._subintegration = subintegration

