# coding: utf-8

"""
    Fingerprint Server API

    Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.   # noqa: E501

    OpenAPI spec version: 3
    Contact: support@fingerprint.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import re  # noqa: F401
from typing import Dict, List, Optional  # noqa: F401
from fingerprint_pro_server_api_sdk.base_model import BaseModel


class IPInfoASN(BaseModel):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'asn': 'str',
        'name': 'str',
        'network': 'str'
    }

    nullable_map = {
        'asn': False,
        'name': False,
        'network': False
    }

    attribute_map = {
        'asn': 'asn',
        'name': 'name',
        'network': 'network'
    }

    def __init__(self, asn=None, name=None, network=None):  # noqa: E501
        """IPInfoASN - a model defined in Swagger"""  # noqa: E501
        self._asn = None
        self._name = None
        self._network = None
        self.discriminator = None
        self.asn = asn
        self.name = name
        self.network = network

    @property
    def asn(self) -> str:
        """Gets the asn of this IPInfoASN.  # noqa: E501


        :return: The asn of this IPInfoASN.  # noqa: E501
        """
        return self._asn

    @asn.setter
    def asn(self, asn: str):
        """Sets the asn of this IPInfoASN.


        :param asn: The asn of this IPInfoASN.  # noqa: E501
        """
        if asn is None:
            raise ValueError("Invalid value for `asn`, must not be `None`")  # noqa: E501

        self._asn = asn

    @property
    def name(self) -> str:
        """Gets the name of this IPInfoASN.  # noqa: E501


        :return: The name of this IPInfoASN.  # noqa: E501
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this IPInfoASN.


        :param name: The name of this IPInfoASN.  # noqa: E501
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def network(self) -> str:
        """Gets the network of this IPInfoASN.  # noqa: E501


        :return: The network of this IPInfoASN.  # noqa: E501
        """
        return self._network

    @network.setter
    def network(self, network: str):
        """Sets the network of this IPInfoASN.


        :param network: The network of this IPInfoASN.  # noqa: E501
        """
        if network is None:
            raise ValueError("Invalid value for `network`, must not be `None`")  # noqa: E501

        self._network = network

