# coding: utf-8

"""
    Fingerprint Pro Server API

    Fingerprint Pro Server API allows you to get information about visitors and about individual events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.   # noqa: E501

    OpenAPI spec version: 3
    Contact: support@fingerprint.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import re  # noqa: F401
from typing import Dict, List, Optional  # noqa: F401
from fingerprint_pro_server_api_sdk.base_model import BaseModel


class Subdivision(BaseModel):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'iso_code': 'str',
        'name': 'str'
    }

    attribute_map = {
        'iso_code': 'isoCode',
        'name': 'name'
    }

    def __init__(self, iso_code=None, name=None):  # noqa: E501
        """Subdivision - a model defined in Swagger"""  # noqa: E501
        self._iso_code = None
        self._name = None
        self.discriminator = None
        if iso_code is not None:
            self.iso_code = iso_code
        if name is not None:
            self.name = name

    @property
    def iso_code(self) -> Optional[str]:
        """Gets the iso_code of this Subdivision.  # noqa: E501


        :return: The iso_code of this Subdivision.  # noqa: E501
        """
        return self._iso_code

    @iso_code.setter
    def iso_code(self, iso_code: Optional[str]):
        """Sets the iso_code of this Subdivision.


        :param iso_code: The iso_code of this Subdivision.  # noqa: E501
        """

        self._iso_code = iso_code

    @property
    def name(self) -> Optional[str]:
        """Gets the name of this Subdivision.  # noqa: E501


        :return: The name of this Subdivision.  # noqa: E501
        """
        return self._name

    @name.setter
    def name(self, name: Optional[str]):
        """Sets the name of this Subdivision.


        :param name: The name of this Subdivision.  # noqa: E501
        """

        self._name = name

