# coding: utf-8

"""
    Fingerprint server API

    Schema describes Fingerprint public server API  # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BaseResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'visitor_id': 'str',
        'visits': 'list[Visit]'
    }

    attribute_map = {
        'visitor_id': 'visitorId',
        'visits': 'visits'
    }

    def __init__(self, visitor_id=None, visits=None):  # noqa: E501
        """BaseResponse - a model defined in Swagger"""  # noqa: E501
        self._visitor_id = None
        self._visits = None
        self.discriminator = None
        self.visitor_id = visitor_id
        self.visits = visits

    @property
    def visitor_id(self):
        """Gets the visitor_id of this BaseResponse.  # noqa: E501


        :return: The visitor_id of this BaseResponse.  # noqa: E501
        :rtype: str
        """
        return self._visitor_id

    @visitor_id.setter
    def visitor_id(self, visitor_id):
        """Sets the visitor_id of this BaseResponse.


        :param visitor_id: The visitor_id of this BaseResponse.  # noqa: E501
        :type: str
        """
        if visitor_id is None:
            raise ValueError("Invalid value for `visitor_id`, must not be `None`")  # noqa: E501

        self._visitor_id = visitor_id

    @property
    def visits(self):
        """Gets the visits of this BaseResponse.  # noqa: E501


        :return: The visits of this BaseResponse.  # noqa: E501
        :rtype: list[Visit]
        """
        return self._visits

    @visits.setter
    def visits(self, visits):
        """Sets the visits of this BaseResponse.


        :param visits: The visits of this BaseResponse.  # noqa: E501
        :type: list[Visit]
        """
        if visits is None:
            raise ValueError("Invalid value for `visits`, must not be `None`")  # noqa: E501

        self._visits = visits

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BaseResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BaseResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
