"""
Server API
Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios.
Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
The API also supports collection of Automation Intelligence for requests to your server in edge, pre-origin, or middleware contexts.

The version of the OpenAPI document: 4
Contact: support@fingerprint.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ErrorCode(str, Enum):
    """
    Error code: * `request_cannot_be_parsed` - The query parameters or JSON payload contains some errors   that prevented us from parsing it (wrong type/surpassed limits). * `request_read_timeout` - The request body could not be read before the connection timed out. * `secret_api_key_required` - secret API key in header is missing or empty. * `secret_api_key_not_found` - No Fingerprint workspace found for specified secret API key. * `public_api_key_required` - public API key in header is missing or empty. * `public_api_key_not_found` - No Fingerprint workspace found for specified public API key. * `subscription_not_active` - Fingerprint workspace is not active. * `wrong_region` - Server and workspace region differ. * `feature_not_enabled` - This feature (for example, Delete API) is not enabled for your workspace. * `visitor_not_found` - The specified visitor ID was not found. It never existed or it may have already been deleted. * `too_many_requests` - The limit on secret API key requests per second has been exceeded. * `state_not_ready` - The event specified with event ID is   not ready for updates yet. Try again.   This error happens in rare cases when update API is called immediately   after receiving the event ID on the client. In case you need to send   information right away, we recommend using the JS agent API instead. * `failed` - Internal server error. * `event_not_found` - The specified event ID was not found. It never existed, expired, or it has been deleted. * `missing_module` - The request is invalid because it is missing a required module. * `payload_too_large` - The request payload is too large and cannot be processed. * `service_unavailable` - The service was unable to process the request. * `ruleset_not_found` - The specified ruleset was not found. It never existed or it has been deleted. 
    """

    """
    allowed enum values
    """
    REQUEST_CANNOT_BE_PARSED = 'request_cannot_be_parsed'
    REQUEST_READ_TIMEOUT = 'request_read_timeout'
    SECRET_API_KEY_REQUIRED = 'secret_api_key_required'
    SECRET_API_KEY_NOT_FOUND = 'secret_api_key_not_found'
    PUBLIC_API_KEY_REQUIRED = 'public_api_key_required'
    PUBLIC_API_KEY_NOT_FOUND = 'public_api_key_not_found'
    SUBSCRIPTION_NOT_ACTIVE = 'subscription_not_active'
    WRONG_REGION = 'wrong_region'
    FEATURE_NOT_ENABLED = 'feature_not_enabled'
    VISITOR_NOT_FOUND = 'visitor_not_found'
    TOO_MANY_REQUESTS = 'too_many_requests'
    STATE_NOT_READY = 'state_not_ready'
    FAILED = 'failed'
    EVENT_NOT_FOUND = 'event_not_found'
    MISSING_MODULE = 'missing_module'
    PAYLOAD_TOO_LARGE = 'payload_too_large'
    SERVICE_UNAVAILABLE = 'service_unavailable'
    RULESET_NOT_FOUND = 'ruleset_not_found'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ErrorCode from a JSON string"""
        return cls(json.loads(json_str))

    @classmethod
    def _missing_(cls, value: object) -> Self:
        """Accept unknown enum values gracefully."""
        if not isinstance(value, str):
            raise ValueError(f"{value!r} is not a valid {cls.__name__}")
        obj = str.__new__(cls, value)
        obj._name_ = str(value)
        obj._value_ = value
        # cache it so the same value won't trigger `_missing_` again
        cls._value2member_map_[value] = obj
        return obj
