"""
Server API
Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios.
Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
The API also supports collection of Automation Intelligence for requests to your server in edge, pre-origin, or middleware contexts.

The version of the OpenAPI document: 4
Contact: support@fingerprint.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Optional

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from fingerprint_server_sdk.models.bot_info import BotInfo
from fingerprint_server_sdk.models.event_source import EventSource
from fingerprint_server_sdk.models.ip_info import IPInfo
from fingerprint_server_sdk.models.proxy_confidence import ProxyConfidence
from fingerprint_server_sdk.models.proxy_details import ProxyDetails
from fingerprint_server_sdk.models.vpn_confidence import VpnConfidence
from fingerprint_server_sdk.models.vpn_methods import VpnMethods
from typing_extensions import Self


class EventEdge(BaseModel):
    """
    IP and bot analysis for an event generated by the Automation Intelligence API (`/edge` endpoint). No client-side collection agent is involved, so Identification (`visitor_id`) and device-telemetry-derived Smart Signals are not available. 
    """

    event_id: StrictStr = Field(description="Unique identifier of the user's request. The first portion of the event_id is a unix epoch milliseconds timestamp. ")
    timestamp: StrictInt = Field(description="Timestamp of the event with millisecond precision in Unix time.")
    linked_id: Optional[StrictStr] = Field(default=None, description="A customer-provided id that was sent with the request.")
    tags: Optional[Dict[str, Any]] = Field(default=None, description="A customer-provided value or an object that was sent with the identification request or updated later.")
    url: Optional[StrictStr] = Field(default=None, description="Page URL from which the request was sent.")
    bot_info: Optional[BotInfo] = None
    ip_info: IPInfo
    proxy: Optional[StrictBool] = Field(default=None, description="IP address was used by a public proxy provider or belonged to a known recent residential proxy ")
    proxy_confidence: Optional[ProxyConfidence] = None
    proxy_details: Optional[ProxyDetails] = None
    vpn: Optional[StrictBool] = Field(default=None, description="VPN or other anonymizing service has been used when sending the request. ")
    vpn_confidence: Optional[VpnConfidence] = None
    vpn_methods: Optional[VpnMethods] = None
    source: EventSource
    __properties: ClassVar[list[str]] = ['event_id', 'timestamp', 'linked_id', 'tags', 'url', 'bot_info', 'ip_info', 'proxy', 'proxy_confidence', 'proxy_details', 'vpn', 'vpn_confidence', 'vpn_methods', 'source']

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EventEdge from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of bot_info
        if self.bot_info:
            _dict['bot_info'] = self.bot_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ip_info
        if self.ip_info:
            _dict['ip_info'] = self.ip_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of proxy_details
        if self.proxy_details:
            _dict['proxy_details'] = self.proxy_details.to_dict()
        # override the default output from pydantic by calling `to_dict()` of vpn_methods
        if self.vpn_methods:
            _dict['vpn_methods'] = self.vpn_methods.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EventEdge from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "event_id": obj.get("event_id"),
            "timestamp": obj.get("timestamp"),
            "linked_id": obj.get("linked_id"),
            "tags": obj.get("tags"),
            "url": obj.get("url"),
            "bot_info": BotInfo.from_dict(obj["bot_info"]) if obj.get("bot_info") is not None else None,
            "ip_info": IPInfo.from_dict(obj["ip_info"]) if obj.get("ip_info") is not None else None,
            "proxy": obj.get("proxy"),
            "proxy_confidence": obj.get("proxy_confidence"),
            "proxy_details": ProxyDetails.from_dict(obj["proxy_details"]) if obj.get("proxy_details") is not None else None,
            "vpn": obj.get("vpn"),
            "vpn_confidence": obj.get("vpn_confidence"),
            "vpn_methods": VpnMethods.from_dict(obj["vpn_methods"]) if obj.get("vpn_methods") is not None else None,
            "source": obj.get("source")
        })
        return _obj


