"""
Server API
Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios.
Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
The API also supports collection of Automation Intelligence for requests to your server in edge, pre-origin, or middleware contexts.

The version of the OpenAPI document: 4
Contact: support@fingerprint.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class EventSource(str, Enum):
    """
    Identifies how the event was generated. - `device` - the event was generated by the JS agent or a mobile SDK running on an end-user device. - `edge` - the event was generated by the Automation Intelligence API (`/edge` endpoint), analyzing a request intercepted at the edge. 
    """

    """
    allowed enum values
    """
    DEVICE = 'device'
    EDGE = 'edge'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EventSource from a JSON string"""
        return cls(json.loads(json_str))

    @classmethod
    def _missing_(cls, value: object) -> Self:
        """Accept unknown enum values gracefully."""
        if not isinstance(value, str):
            raise ValueError(f"{value!r} is not a valid {cls.__name__}")
        obj = str.__new__(cls, value)
        obj._name_ = str(value)
        obj._value_ = value
        # cache it so the same value won't trigger `_missing_` again
        cls._value2member_map_[value] = obj
        return obj
