"""
Server API
Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios.
Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
The API also supports collection of Automation Intelligence for requests to your server in edge, pre-origin, or middleware contexts.

The version of the OpenAPI document: 4
Contact: support@fingerprint.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Optional

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from fingerprint_server_sdk.models.request_header_modifications import RequestHeaderModifications
from fingerprint_server_sdk.models.rule_action_type import RuleActionType
from typing_extensions import Self


class EventRuleActionAllow(BaseModel):
    """
    Informs the client that the request should be forwarded to the origin with optional request header modifications.
    """

    ruleset_id: StrictStr = Field(description="The ID of the evaluated ruleset.")
    rule_id: Optional[StrictStr] = Field(default=None, description="The ID of the rule that matched the identification event.")
    rule_expression: Optional[StrictStr] = Field(default=None, description="The expression of the rule that matched the identification event.")
    type: RuleActionType
    request_header_modifications: Optional[RequestHeaderModifications] = None
    __properties: ClassVar[list[str]] = ['ruleset_id', 'rule_id', 'rule_expression', 'type', 'request_header_modifications']

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EventRuleActionAllow from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of request_header_modifications
        if self.request_header_modifications:
            _dict['request_header_modifications'] = self.request_header_modifications.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EventRuleActionAllow from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ruleset_id": obj.get("ruleset_id"),
            "rule_id": obj.get("rule_id"),
            "rule_expression": obj.get("rule_expression"),
            "type": obj.get("type"),
            "request_header_modifications": RequestHeaderModifications.from_dict(obj["request_header_modifications"]) if obj.get("request_header_modifications") is not None else None
        })
        return _obj


