"""
Server API
Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios.
Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
The API also supports collection of Automation Intelligence for requests to your server in edge, pre-origin, or middleware contexts.

The version of the OpenAPI document: 4
Contact: support@fingerprint.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Optional

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from fingerprint_server_sdk.models.geolocation import Geolocation
from typing_extensions import Self


class IPInfoV4(BaseModel):
    """
    IPInfoV4
    """

    address: StrictStr
    geolocation: Optional[Geolocation] = None
    asn: Optional[StrictStr] = None
    asn_name: Optional[StrictStr] = None
    asn_network: Optional[StrictStr] = None
    asn_type: Optional[StrictStr] = None
    datacenter_result: Optional[StrictBool] = Field(default=None, description="When true, the request originated from a datacenter.")
    datacenter_name: Optional[StrictStr] = None
    __properties: ClassVar[list[str]] = ['address', 'geolocation', 'asn', 'asn_name', 'asn_network', 'asn_type', 'datacenter_result', 'datacenter_name']

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IPInfoV4 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of geolocation
        if self.geolocation:
            _dict['geolocation'] = self.geolocation.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IPInfoV4 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": obj.get("address"),
            "geolocation": Geolocation.from_dict(obj["geolocation"]) if obj.get("geolocation") is not None else None,
            "asn": obj.get("asn"),
            "asn_name": obj.get("asn_name"),
            "asn_network": obj.get("asn_network"),
            "asn_type": obj.get("asn_type"),
            "datacenter_result": obj.get("datacenter_result"),
            "datacenter_name": obj.get("datacenter_name")
        })
        return _obj


