"""
Server API
Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios.
Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
The API also supports collection of Automation Intelligence for requests to your server in edge, pre-origin, or middleware contexts.

The version of the OpenAPI document: 4
Contact: support@fingerprint.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class RareDevicePercentileBucket(str, Enum):
    """
    The rarity percentile bucket of the device, indicating how uncommon the device configuration is compared to all observed devices.  > This Smart Signal is currently in beta and only available to select customers. If you are interested, please [contact our support team](https://fingerprint.com/support/). 
    """

    """
    allowed enum values
    """
    LESS_THAN_P95 = '<p95'
    P95_MINUS_P99 = 'p95-p99'
    P99_MINUS_P99_DOT_5 = 'p99-p99.5'
    P99_DOT_5_MINUS_P99_DOT_9 = 'p99.5-p99.9'
    P99_DOT_9_PLUS = 'p99.9+'
    NOT_SEEN = 'not_seen'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RareDevicePercentileBucket from a JSON string"""
        return cls(json.loads(json_str))

    @classmethod
    def _missing_(cls, value: object) -> Self:
        """Accept unknown enum values gracefully."""
        if not isinstance(value, str):
            raise ValueError(f"{value!r} is not a valid {cls.__name__}")
        obj = str.__new__(cls, value)
        obj._name_ = str(value)
        obj._value_ = value
        # cache it so the same value won't trigger `_missing_` again
        cls._value2member_map_[value] = obj
        return obj
