name: 'coverage-report'
on:
  push:
    branches:
      - main
      - coverage # remove before merge to main

concurrency:
  group: coverage-report-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: true
          python-version: "3.13"
      - name: "Install dependencies"
        run: uv sync
      - name: "Generate coverage"
        run: |
          uv run coverage run --source=fingerprint_server_sdk -m pytest
          uv run coverage html
          uv run coverage json
          uv run python ./generate_coverage_summary.py
          rm ./htmlcov/.gitignore

      - name: Create Coverage Badges
        uses: jaywcjlove/coverage-badges-cli@998665f7962b1a3935ba8c3e786171a99436e5d1 # v2.3.0
        with:
          source: coverage-summary.json
          output: htmlcov/badges.svg
          jsonPath: total.statements.pct

      - name: Upload GitHub Pages artifact 📦
        uses: actions/upload-pages-artifact@v5
        with:
          path: htmlcov

  deploy-pages:
    name: Deploy to GitHub Pages 🚀
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
