name: 'Publish'
on:
  release:
    types:
      - published

jobs:
  publish:
    name: 'Publish to PyPI'
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/fingerprint-pro-server-api-sdk
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Install Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 'Build'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install wheel
          pip install twine

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@897895f1e160c830e369f9779632ebc134688e1b


