name: 'Publish'
on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string
        description: Tag name to release

jobs:
  publish:
    name: 'Publish to PyPI'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://pypi.org/p/fingerprint-pro-server-api-sdk
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        if: github.event_name == 'release'
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: 'Checkout repository'
        uses: actions/checkout@v4
        if: github.event_name == 'workflow_dispatch'
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: 'Install Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 'Build'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install wheel
          pip install twine
          python setup.py sdist bdist_wheel

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@897895f1e160c830e369f9779632ebc134688e1b

  e2e-tests:
    needs: publish
    uses: ./.github/workflows/e2e-tests.yml


