name: 'Release'
on:
  push:
    branches:
      - main
      - dev

jobs:
  release:
    name: 'Release project'
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/release-sdk-changesets.yml@e30d3a9938e5398ede80e1ea7651c0f2b477a7de
    with:
      appId: ${{ vars.APP_ID }}
      runnerAppId: ${{ vars.RUNNER_APP_ID }}
      version-command: bash ./changeset-version.sh
      publish-command: bash ./changeset-publish.sh
      language: python
      language-version: '3.12'
      prepare-command: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install wheel
        pip install twine
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      RUNNER_APP_PRIVATE_KEY: ${{ secrets.RUNNER_APP_PRIVATE_KEY }}
